# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(385, 468)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scanPortRangeLabel = QtWidgets.QLabel(self.centralwidget)
        self.scanPortRangeLabel.setGeometry(QtCore.QRect(90, 80, 131, 31))
        self.scanPortRangeLabel.setObjectName("scanPortRangeLabel")
        self.portStartRangeTxtBox = QtWidgets.QLineEdit(self.centralwidget)
        self.portStartRangeTxtBox.setGeometry(QtCore.QRect(150, 120, 113, 25))
        self.portStartRangeTxtBox.setObjectName("portStartRangeTxtBox")
        self.portEndrangeTxtBox = QtWidgets.QLineEdit(self.centralwidget)
        self.portEndrangeTxtBox.setGeometry(QtCore.QRect(150, 180, 113, 25))
        self.portEndrangeTxtBox.setObjectName("portEndrangeTxtBox")
        self.scanPortRangeLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.scanPortRangeLabel_2.setGeometry(QtCore.QRect(40, 120, 91, 31))
        self.scanPortRangeLabel_2.setObjectName("scanPortRangeLabel_2")
        self.scanPortRangeLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.scanPortRangeLabel_3.setGeometry(QtCore.QRect(40, 180, 91, 31))
        self.scanPortRangeLabel_3.setObjectName("scanPortRangeLabel_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 260, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.scanPortLabel = QtWidgets.QLabel(self.centralwidget)
        self.scanPortLabel.setGeometry(QtCore.QRect(30, 10, 71, 25))
        self.scanPortLabel.setObjectName("scanPortLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 385, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.scanPortRangeLabel.setText(_translate("MainWindow", "Port scan range"))
        self.scanPortRangeLabel_2.setText(_translate("MainWindow", "Start range"))
        self.scanPortRangeLabel_3.setText(_translate("MainWindow", "End range"))
        self.pushButton.setText(_translate("MainWindow", "Scan"))
        self.scanPortLabel.setText(_translate("MainWindow", "Scan ports"))
